I'<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Event;
use App\Models\Location;
use App\Models\Sponsor;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Seed the events table with sample TDU events.
     */
    public function run(): void
    {
        // Get IDs for relationships
        $categories = Category::pluck('id', 'slug');
        $sponsors = Sponsor::pluck('id', 'slug');
        $locations = Location::pluck('id', 'name');

        $events = [
            // Stage Races (Free to watch)
            [
                'title' => 'Stage 1: Adelaide City Circuit',
                'description' => 'The Tour kicks off with an exciting city circuit race through the heart of Adelaide. Watch the peloton navigate tight corners and sprint finishes on this fast, technical course.',
                'start_datetime' => '2026-01-20 10:00:00',
                'end_datetime' => '2026-01-20 14:00:00',
                'category_id' => $categories['road-race'],
                'sponsor_id' => $sponsors['santos'],
                'location_id' => $locations['Adelaide City'],
                'ride_distance_km' => 51.0,
                'elevation_gain_m' => 120,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/stage-1',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Stage 2: Tanunda to Angaston',
                'description' => 'A stunning ride through the Barossa Valley wine region. Rolling hills and picturesque vineyards provide the backdrop for this challenging stage.',
                'start_datetime' => '2026-01-21 09:30:00',
                'end_datetime' => '2026-01-21 14:30:00',
                'category_id' => $categories['road-race'],
                'sponsor_id' => $sponsors['santos'],
                'location_id' => $locations['Tanunda'],
                'ride_distance_km' => 145.0,
                'elevation_gain_m' => 1850,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/stage-2',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Stage 3: Victor Harbor Circuit',
                'description' => 'Coastal racing at its finest. The peloton battles ocean winds and scenic clifftop roads in this spectacular seaside stage.',
                'start_datetime' => '2026-01-22 10:00:00',
                'end_datetime' => '2026-01-22 15:00:00',
                'category_id' => $categories['road-race'],
                'sponsor_id' => $sponsors['santos'],
                'location_id' => $locations['Victor Harbor'],
                'ride_distance_km' => 138.5,
                'elevation_gain_m' => 1420,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/stage-3',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Stage 4: McLaren Vale to Willunga Hill',
                'description' => 'The Queen Stage! The iconic Willunga Hill climb decides the overall classification. Two ascents of the famous climb will test the best climbers.',
                'start_datetime' => '2026-01-23 09:00:00',
                'end_datetime' => '2026-01-23 15:30:00',
                'category_id' => $categories['hill-climb'],
                'sponsor_id' => $sponsors['santos'],
                'location_id' => $locations['Willunga Hill'],
                'ride_distance_km' => 151.5,
                'elevation_gain_m' => 2650,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/stage-4',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Stage 5: Adelaide City Criterium',
                'description' => 'The final stage concludes with a thrilling criterium through Adelaide\'s streets. Fast corners and bunch sprints provide a fitting finale.',
                'start_datetime' => '2026-01-24 11:00:00',
                'end_datetime' => '2026-01-24 14:00:00',
                'category_id' => $categories['criterium'],
                'sponsor_id' => $sponsors['santos'],
                'location_id' => $locations['Adelaide City'],
                'ride_distance_km' => 90.0,
                'elevation_gain_m' => 85,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/stage-5',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],

            // Community Events (Paid registration)
            [
                'title' => 'Bupa Challenge Tour - Long Course',
                'description' => 'Take on the challenge of riding the same roads as the professionals! The long course offers a true test for experienced cyclists.',
                'start_datetime' => '2026-01-19 06:00:00',
                'end_datetime' => '2026-01-19 14:00:00',
                'category_id' => $categories['gran-fondo'],
                'sponsor_id' => $sponsors['bupa'],
                'location_id' => $locations['McLaren Vale'],
                'ride_distance_km' => 152.0,
                'elevation_gain_m' => 2100,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/challenge-tour',
                'min_cost' => 175.00,
                'max_cost' => 175.00,
                'is_free' => false,
            ],
            [
                'title' => 'Bupa Challenge Tour - Medium Course',
                'description' => 'A challenging but achievable ride through the beautiful Adelaide Hills. Perfect for intermediate cyclists looking to push their limits.',
                'start_datetime' => '2026-01-19 07:00:00',
                'end_datetime' => '2026-01-19 13:00:00',
                'category_id' => $categories['gran-fondo'],
                'sponsor_id' => $sponsors['bupa'],
                'location_id' => $locations['McLaren Vale'],
                'ride_distance_km' => 100.0,
                'elevation_gain_m' => 1200,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/challenge-tour',
                'min_cost' => 145.00,
                'max_cost' => 145.00,
                'is_free' => false,
            ],
            [
                'title' => 'Bupa Challenge Tour - Short Course',
                'description' => 'An accessible ride for all fitness levels. Experience the excitement of closed roads and a festival atmosphere.',
                'start_datetime' => '2026-01-19 08:00:00',
                'end_datetime' => '2026-01-19 12:00:00',
                'category_id' => $categories['community-ride'],
                'sponsor_id' => $sponsors['bupa'],
                'location_id' => $locations['McLaren Vale'],
                'ride_distance_km' => 50.0,
                'elevation_gain_m' => 450,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/challenge-tour',
                'min_cost' => 95.00,
                'max_cost' => 95.00,
                'is_free' => false,
            ],
            [
                'title' => 'Glenelg Community Criterium',
                'description' => 'A fun, family-friendly criterium event at Glenelg beach. Categories for all ages and abilities with spot prizes and festivities.',
                'start_datetime' => '2026-01-18 09:00:00',
                'end_datetime' => '2026-01-18 13:00:00',
                'category_id' => $categories['criterium'],
                'sponsor_id' => $sponsors['adelaide-city-council'],
                'location_id' => $locations['Glenelg'],
                'ride_distance_km' => null,
                'elevation_gain_m' => null,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/community-crit',
                'min_cost' => 25.00,
                'max_cost' => 25.00,
                'is_free' => false,
            ],
            [
                'title' => 'Kids Tour - Adelaide',
                'description' => 'Introduce the little ones to cycling! A safe, traffic-free course in the parklands with plenty of fun activities and prizes for all participants.',
                'start_datetime' => '2026-01-18 10:00:00',
                'end_datetime' => '2026-01-18 12:00:00',
                'category_id' => $categories['kids-race'],
                'sponsor_id' => $sponsors['specialized'],
                'location_id' => $locations['Adelaide City'],
                'ride_distance_km' => null,
                'elevation_gain_m' => null,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/kids-tour',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],

            // Festival Events (Free)
            [
                'title' => 'TDU Festival Hub - Adelaide',
                'description' => 'The heart of the Tour Down Under! Live music, food trucks, cycling expo, team presentations, and giant screens showing all the racing action.',
                'start_datetime' => '2026-01-18 10:00:00',
                'end_datetime' => '2026-01-24 20:00:00',
                'category_id' => $categories['festival-event'],
                'sponsor_id' => $sponsors['sa-tourism'],
                'location_id' => $locations['Adelaide City'],
                'ride_distance_km' => null,
                'elevation_gain_m' => null,
                'is_featured' => true,
                'url' => 'https://allthetdu.com/festival',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Hahndorf Street Party',
                'description' => 'Experience German heritage meets cycling culture! Live music, local wines, artisan food, and family entertainment in this charming Adelaide Hills town.',
                'start_datetime' => '2026-01-21 16:00:00',
                'end_datetime' => '2026-01-21 22:00:00',
                'category_id' => $categories['festival-event'],
                'sponsor_id' => $sponsors['sa-tourism'],
                'location_id' => $locations['Hahndorf'],
                'ride_distance_km' => null,
                'elevation_gain_m' => null,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/hahndorf',
                'min_cost' => null,
                'max_cost' => null,
                'is_free' => true,
            ],
            [
                'title' => 'Norwood Parade Time Trial',
                'description' => 'An individual time trial along The Parade. Test yourself against the clock on this flat, fast course.',
                'start_datetime' => '2026-01-17 14:00:00',
                'end_datetime' => '2026-01-17 18:00:00',
                'category_id' => $categories['time-trial'],
                'sponsor_id' => $sponsors['trek-bikes'],
                'location_id' => $locations['Norwood'],
                'ride_distance_km' => 20.0,
                'elevation_gain_m' => 25,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/time-trial',
                'min_cost' => 45.00,
                'max_cost' => 45.00,
                'is_free' => false,
            ],
            [
                'title' => 'Stirling Hill Climb Challenge',
                'description' => 'Think you can climb? Take on the famous Stirling climb and compare your time to the pros. Timed segments with prizes for age group winners.',
                'start_datetime' => '2026-01-19 07:00:00',
                'end_datetime' => '2026-01-19 11:00:00',
                'category_id' => $categories['hill-climb'],
                'sponsor_id' => $sponsors['shimano'],
                'location_id' => $locations['Stirling'],
                'ride_distance_km' => 8.5,
                'elevation_gain_m' => 380,
                'is_featured' => false,
                'url' => 'https://allthetdu.com/hill-climb',
                'min_cost' => 35.00,
                'max_cost' => 35.00,
                'is_free' => false,
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}
